### ISSUE TITLE
Black square while visualizing specific HTAN study

### ISSUE THREAD

**Issue by fedorov** [herrmannlab/slim#96] opened 2022-05-03 16:52 UTC
2.25.305755249420617670925805518669597959172/series/1.3.6.1.4.1.5962.99.1.847101709.1322509636.1650114576141.3.0

![image](https://user-images.githubusercontent.com/313942/166501389-804651e5-d4bf-4a58-a475-20b5306ea5e6.png)

Changing window etc does not seem to have any effect. Zoom feels "jumpy".

**Comment by fedorov** [comment] 2022-05-03 16:54
This one doesn't seem to work either 2.25.253443077977640338251305809014416841249/series/1.3.6.1.4.1.5962.99.1.847223301.1587446896.1650114697733.3.0

**Comment by hackermd** [comment] 2022-05-12 21:41
These image appear in fact to be "empty". I will need to investigate further.

@dclunie could you please also take a look at the original source images?

**Comment by fedorov** [comment] 2022-05-17 14:22
Every single multichannel one I tried that have HTA12 appear to have this issue.

**Comment by hackermd** [comment] 2022-05-17 18:11
These images have a very low dynamic range (shown here using the UI of the the latest dev version):

![Screen Shot 2022-05-17 at 2 08 46 PM](https://user-images.githubusercontent.com/6855297/168881019-f03b6048-c53d-459f-b3f2-134e8a2ea25a.png)

With the improved display setting interface (will become available in 0.6.0), it will be easier to set the value of interest window.

However, these images clearly have issues.

**Comment by fedorov** [comment] 2022-05-17 18:17
So is it the plan to initialize those settings automatically to some meaningful values?

Otherwise I am not sure what is the sequence of steps for the user to discover how to populate those settings. I understand it might be difficult since you don't know the entire image range, but even initializing based on the range observed in the data already fetched would be so much better than the current behavior.

**Comment by hackermd** [comment] 2022-05-17 18:52
To me, these are two related, but separate issues. #99 is about improving the default display settings and choosing other (more "meaningful") limit values. This issue is about the images having very low values.

I will close this issue, since the problem is the data. We can continue the conversation regarding default display settings on #99.

**Closed by hackermd** 2022-05-17 18:52 UTC
Labels: data, idc:priority
